[package]
name = "ConstantProduct"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]
version = "1.0.0"

[dependencies]

[addresses]
constant_product = "0x0"
