[package]
name = "memez_v2_invariant"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }


[addresses]
memez_v2_invariant = "0x0"
std = "0x1"
sui = "0x2"
